# Generated by Django 5.1 on 2024-08-27 20:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_create_imagegallerypage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 2), ("paragraph", 3), ("image", 7), ("embed", 8)],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")],
                            "help_text": 'Please ensure that you do not skip heading levels. For example, the next heading after an H2 should only be either an H3 or another H2. <a href="https://www.a11yproject.com/posts/how-to-accessible-heading-structure/" target="_blank">Learn more about heading structure</a>',
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.StructBlock", [[("size", 0), ("text", 1)]], {}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Enter a text alternative to be displayed if images fail to load, or to be read by screen reader software. (Overrides the image\'s default alt text.) <a href="https://www.a11yproject.com/posts/alt-text/" target="_blank">Learn more about writing good alt text</a>',
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If this image does not contain meaningful content or is described in nearby text, check this box to not output its alt text.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("alt_text", 5), ("decorative", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"max_height": 400, "max_width": 800},
                    ),
                },
            ),
        ),
    ]
