# Generated by Django 5.1.1 on 2024-09-12 23:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0001_initial'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_media.customimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
